### ISSUE TITLE
Delay property doesn't appear to have any effect in delay.yaml

### ISSUE THREAD

**Issue by gctucker** [GENIVI/vehicle_signal_manager#49]
When running the `delay.yaml` sample rule:

```
%YAML 1.2
---
# When the front wipers are enabled, ensure headlights are on (a legal
# requirement in some jurisdictions and generally safer).
- parallel:
    # We now monitor the incoming signal stream for specific conditions to be
    # met.
    - condition: wipers.front.on == true

      # Emit a signal to turn on the headlights
      emit:
          # How many msec to wait after condition changes before we emit the
          # signal.
          #
          # The delay in this use case is arbitrary and exaggerated so this
          # configuration file can be used to test the delay feature.
          delay: 2000

          signal: lights.external.headlights
          value: true
```

and sending the `wipers.front.on` signal manually, the `lights.external.headlights` should only change its value after 2 seconds but appears to not be ignoring the `delay: 2000` property:

```
$ ./vsm --signal-number-file signal_number_maps/samples.vsi sample_rules/delay.yaml
wipers.front.on = True
> 1963,wipers.front.on,5020,'True'
< 1964,lights.external.headlights,19,'True'
```

The `1963` timestamp here is the time when the manual signal was sent.
